name: Deploy to Logto Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Logto Cloud
        env:
          LOGTO_AUTH: ${{ secrets.LOGTO_AUTH }} # Your M2M credentials
          LOGTO_ENDPOINT: ${{ secrets.LOGTO_ENDPOINT }} # Your Logto endpoint
          LOGTO_RESOURCE: ${{ secrets.LOGTO_RESOURCE }} # Your Logto resource
        run: npx logto-tunnel deploy --path ./dist